services:
  nginx:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./dockerfiles
      target: terms-nginx
    image: terms-nginx
    hostname: mashb1t-terms
    container_name: mashb1t-terms
    depends_on:
      - php
    volumes:
      #- ./dockerfiles/php/image-files/var/www/html:/var/www/html
      - ./volumes/storage/app:/var/www/html/storage-nginx/app:ro
    networks:
      - proxy
      - terms
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.terms.rule=Host(`terms.mashb1t.de`)"
      - "traefik.http.routers.terms.entrypoints=websecure"
      - "traefik.http.routers.terms.tls.certresolver=letsencrypt"
      - "traefik.http.services.terms.loadbalancer.server.port=80"
      - "traefik.http.routers.terms.middlewares=cloudflare-ips@file"
      - 'kuma.__web="https://terms.mashb1t.de", "websites"'
      - "resq.enable=true"
#    ports:
#      - "3000:80"

  php:
    restart: unless-stopped
    container_name: terms-php
    build:
      dockerfile: Dockerfile
      context: ./dockerfiles
      target: terms-php
    image: terms-php
    command: php-fpm
    networks:
      - terms
    env_file:
      - .env
    volumes:
      #- ./dockerfiles/php/image-files/var/www/html:/var/www/html
      - ./volumes/storage/app:/var/www/html/storage/app:delegated
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    restart: unless-stopped
    image: mysql:8.0
    networks:
      - terms
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - terms-db:/var/lib/mysql
    cap_add:
      - SYS_NICE
   # ports:
   #   - "33006:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "resq.enable=true"
      - "resq.db.type=mysql"
      - "resq.db.user=root"
      - "resq.db.name=all"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - terms
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  terms-db:

networks:
  proxy:
    name: proxy
    external: true
  terms:
