version: "3.9"
services:
  nginx:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./dockerfiles
      target: terms-nginx
    image: terms-nginx
    links:
      - php
    volumes:
      #- ./dockerfiles/php/image-files/var/www/html:/var/www/html
      #      - ./config/terms.mashb1t.de/nginx.conf:/etc/nginx/nginx.conf
      #      - ./config/terms.mashb1t.de/domains:/etc/nginx/conf.d
      - terms-storage:/var/www/html/storage-nginx
    environment:
      - VIRTUAL_HOST=terms.mashb1t.de
      - LETSENCRYPT_HOST=terms.mashb1t.de
      - LETSENCRYPT_EMAIL=info@mash1t.de
#    ports:
#      - "3000:80"
    network_mode: bridge

  php:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./dockerfiles
      target: terms-php
    image: terms-php
    command: php-fpm
    env_file:
      - .env
    volumes:
      #      - ./dockerfiles/php/image-files/var/www/html:/var/www/html
      - terms-storage:/var/www/html/storage
    links:
      - db
      - redis
    network_mode: bridge

  db:
    restart: unless-stopped
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - terms-db:/var/lib/mysql
    cap_add:
      - SYS_NICE
#    ports:
#      - "33006:3306"
    network_mode: bridge

  redis:
    image: redis:6
    restart: always
    network_mode: bridge

volumes:
  terms-db:
  terms-storage:
